# Generated by Django 3.2.6 on 2021-12-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbarContent',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('appearOnNavbar', models.BooleanField(default=False)),
            ],
        ),
    ]
