# Generated by Django 3.2.6 on 2022-01-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0005_myflatpage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflatpage',
            name='color',
            field=models.CharField(default='#096e0f', max_length=7),
        ),
    ]
