# Generated by Django 3.2.6 on 2022-01-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0006_alter_myflatpage_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myflatpage',
            old_name='color',
            new_name='colour',
        ),
    ]
