# Generated by Django 3.2.6 on 2022-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0013_myflatpage_page_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflatpage',
            name='margin_colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
