# Generated by Django 3.2.6 on 2022-01-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0016_myflatpage_appearonsites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflatpage',
            name='appearOnSites',
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='appearOnSites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlineBank.mysite'),
        ),
    ]
