# Generated by Django 3.2.6 on 2022-01-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0017_auto_20220102_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflatpage',
            name='appearOnSites',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onlineBank.mysite'),
        ),
    ]
