# Generated by Django 3.2.6 on 2022-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0020_alter_myflatpage_appearonsites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflatpage',
            name='footer_colour',
        ),
        migrations.RemoveField(
            model_name='myflatpage',
            name='header_colour',
        ),
        migrations.RemoveField(
            model_name='myflatpage',
            name='margin_colour',
        ),
        migrations.AddField(
            model_name='mysite',
            name='footer_colour',
            field=models.CharField(default='#096e0f', max_length=7),
        ),
        migrations.AddField(
            model_name='mysite',
            name='header_colour',
            field=models.CharField(default='#096e0f', max_length=7),
        ),
        migrations.AddField(
            model_name='mysite',
            name='margin_colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
