# Generated by Django 3.2.6 on 2022-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0024_alter_innertemplate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innertemplate',
            name='file',
            field=models.FileField(upload_to='onlineBank/templates/flatpages'),
        ),
    ]
