# Generated by Django 3.2.6 on 2022-01-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0028_mysite_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='staticFile',
            fields=[
                ('name', models.CharField(default='random', max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='onlineBank/static')),
            ],
        ),
    ]
