# Generated by Django 3.2.6 on 2022-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0029_staticfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfile',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
