# Generated by Django 3.2.6 on 2022-01-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0034_rename_acccountname_account_accountname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountSortCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
