# Generated by Django 3.2.6 on 2022-01-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('onlineBank', '0002_alter_navbarcontent_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('appearOnNavbar', models.BooleanField(default=False)),
            ],
            bases=('flatpages.flatpage',),
        ),
        migrations.DeleteModel(
            name='navbarContent',
        ),
    ]
