# Generated by Django 3.2.6 on 2022-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0004_myflatpage_appearonfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflatpage',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
    ]
