# Generated by Django 3.2.6 on 2022-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0011_rename_primarycolour_myflatpage_primary_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myflatpage',
            old_name='primary_colour',
            new_name='footer_colour',
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='header_colour',
            field=models.CharField(default='#096e0f', max_length=7),
        ),
    ]
