# Generated by Django 3.2.6 on 2022-01-02 13:21

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('onlineBank', '0014_myflatpage_margin_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.site')),
                ('bankName', models.CharField(default='West Midlands Regional Bank', max_length=50)),
            ],
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
