# Generated by Django 3.2.6 on 2022-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0015_mysite'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflatpage',
            name='appearOnSites',
            field=models.ManyToManyField(to='onlineBank.MySite'),
        ),
    ]
