# Generated by Django 3.2.6 on 2022-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0022_innertemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innertemplate',
            name='id',
        ),
        migrations.AlterField(
            model_name='innertemplate',
            name='name',
            field=models.CharField(default='template.html', max_length=50, primary_key=True, serialize=False),
        ),
    ]
