# Generated by Django 3.2.6 on 2022-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0023_auto_20220102_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innertemplate',
            name='file',
            field=models.FileField(upload_to='onlineBank/static/templates/flatpages'),
        ),
    ]
