# Generated by Django 3.2.6 on 2022-01-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0030_alter_staticfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='onlineBank/static/logo')),
            ],
        ),
    ]
