# Generated by Django 3.2.6 on 2022-01-03 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onlineBank.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineBank', '0032_mysite_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('accountNumber', models.CharField(default=onlineBank.models.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('acccountName', models.CharField(default='Current Account', max_length=20)),
                ('accountBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accountOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
