# Generated by Django 3.2.6 on 2022-01-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0033_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acccountName',
            new_name='accountName',
        ),
    ]
