# Generated by Django 3.2.8 on 2022-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0039_ip_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='country',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
