# Generated by Django 3.2.8 on 2022-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0041_auto_20220113_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='isp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='latitude',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='longitude',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='postal',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
