# Generated by Django 3.2.8 on 2022-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0046_alter_mysite_malwarefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sortCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
