# Generated by Django 3.2.8 on 2022-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0048_rename_sortcode_transaction_othersortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='Title_font_colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
