# Generated by Django 3.2.8 on 2022-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0051_alter_myflatpage_text_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='font',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='onlineBank/static/fonts')),
            ],
        ),
    ]
