# Generated by Django 3.2.8 on 2022-01-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0052_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineBank.font'),
        ),
    ]
