# Generated by Django 3.2.6 on 2022-01-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineBank', '0054_mysite_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysite',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='mysite',
            name='domain_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
